1:
  - [3, 0]
  - [2,0]
  - [10,0]
  - [9,0]
  - [24,0]
  - [11,0]
  - [12,0]
  - [15,0]
  - [17,0]
  - [18,0]
  - [19,0]
  - [1,0]
  - [2,0]
  - [3,0]
2:
  - [3, 0]
  - [4, 0]
  - [5, 0]
  - [6, 0]
  - [7, 0]
  - [8, 0]
  - [24, 0]
  - [9, 0]
  - [10, 0]
  - [14, 0]
  - [16, 0]
  - [17, 0]
  - [18, 0]
  - [19, 0]
  - [1, 0]
  - [2, 0]
3:
  - [12,0]
  - [15,0]
  - [21,0]
  - [19,0]
  - [18,0]
  - [10,0]
  - [2,0]
  - [3,0]
  - [4,0]
  - [5,0]
  - [6,0]
  - [7,0]
  - [8,0]
  - [11,0]
  - [12,0]
4:
  - [3,0]
  - [2,0]
  - [1,0]
  - [19,0]
  - [18,0]
  - [10,0]
  - [9,0]
  - [24,0]
  - [11,0]
  - [14,0]
  - [18,0]
  - [17,0]
  - [22,0]
  - [23,0]
  - [20,0]
  - [1,0]
  - [2,0]
  - [3,0]
5:
  - [3,0]
  - [4,0]
  - [5,0]
  - [6,0]
  - [7,0]
  - [8,0]
  - [11,0]
  - [12,0]
  - [15,0]
  - [21,0]
  - [19,0]
  - [18,0]
  - [17,0]
  - [16,0]
  - [14,0]
  - [13,0]
  - [12,0]
  - [11,0]
  - [24,0]
  - [9,0]
  - [10,0]
  - [2,0]
  - [3,0]
6:
  - [3,0]
  - [2,0]
  - [1,0]
  - [19,0]
  - [18,0]
  - [11,0]
  - [12,0]
  - [13,0]
  - [14,0]
  - [10,0]
  - [9,0]
  - [24,0]
  - [11,0]
  - [12,0]
  - [13,0]
  - [14,0]
  - [18,0]
  - [17,0]
  - [15,0]
  - [13,0]
  - [14,0]
  - [11,0]
  - [8,0]
  - [7,0]
  - [6,0]
  - [5,0]
  - [4,0]
  - [3,0]
7:
  - [3,0]
  - [2,0]
  - [1,0]
  - [21,0]
  - [22,0]
  - [23,0]
  - [20,0]
  - [21,0]
  - [15,0]
  - [12,0]
  - [11,0]
  - [14,0]
  - [16,0]
  - [17,0]
  - [18,0]
  - [10,0]
  - [9,0]
  - [24,0]
  - [8,0]
  - [7,0]
  - [6,0]
  - [5,0]
  - [4,0]
  - [3,0]
8:
  - [3,0]
  - [2,0]
  - [1,0]
  - [19,0]
  - [18,0]
  - [17,0]
  - [18,0]
  - [10,0]
  - [9,0]
  - [10,0]
  - [14,0]
  - [13,0]
  - [15,0]
  - [17,0]
  - [18,0]
  - [14,0]
  - [13,0]
  - [12,0]
  - [11,0]
  - [8,0]
  - [7,0]
  - [6,0]
  - [5,0]
  - [4,0]
  - [3,0]
9:
  - [3,0]
  - [4,0]
  - [5,0]
  - [6,0]
  - [7,0]
  - [8,0]
  - [24,0]
  - [9,0]
  - [10,0]
  - [11,0]
  - [12,0]
  - [13,0]
  - [14,0]
  - [18,0]
  - [19,0]
  - [1,0]
  - [10,0]
  - [9,0]
  - [24,0]
  - [8,0]
  - [7,0]
  - [6,0]
  - [5,0]
  - [4,0]
  - [3,0]